### ISSUE TITLE
Problem 'delete' button

### ISSUE THREAD

**Issue by jamesvanmil** [jamesvanmil/tricerashopper#171]
Should run test again to verify that it's no longer a problem.

**Comment by crowesn** [comment]
Added stubbed button to show view, labeled 'audit' with tooltip explanation.

**Comment by crowesn** [comment]
It would be cool to rely on the validation and display flash error messages in the views if the audit fails.

**Comment by jamesvanmil** [comment]
Agreed: I was thinking that the button would post to ProblemsController#Audit - this could then delete the record or display the flash message.

**Comment by jamesvanmil** [comment]
I think this process is going to use AJAX btw - a script will run the audit function and fade it out if it suceeds. We'll flash a message in either case.
