### ISSUE TITLE
LMLO add status field and control

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/tricerashopper#262]
Some kind of status feature to indicate and title has been reviewed, replaced, or checked off as no replacement..

**Comment by jamesvanmil** [comment]
This will complicate record keeping, i.e., if you refresh the database for any reason before all the titles are addressed.

**Comment by crowesn** [comment]
I would view this strictly as a convenience feature, a refresh would mean that titles not acted upon would be removed from Sierra and not replaced, right?

## 

Sean Crowe
Digital Analyst and Developer Librarian

Digital Projects and Repositories.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edumailto:sean.crowe@uc.edu
gchat: crowesn

On Apr 26, 2016, at 3:29 PM, James Van Mil <notifications@github.com<mailto:notifications@github.com>> wrote:

This will complicate record keeping, i.e., if you refresh the database for any reason before all the titles are addressed.

**Comment by jamesvanmil** [comment]
yeah - but you're assuming that happens, instead of guarding against it not happening.

https://www.youtube.com/watch?v=siwpn14IE7E

**Comment by crowesn** [comment]
The record keeping is complicated whether we add the convenience feature or not. In cases where the workflow completes without issue: everyone is happy. In cases where there is a refresh associated with a problem, users are in the same situation whether the feature existed or not.
